version: 2

sources:
  - name: staging
    database: "{{ env_var('DBT_DATABASE', 'airbnb-468005') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'airbnb_468005_dataset') }}"

    tables:
      - name: fhv_tripdata
      - name: green_tripdata
      - name: yellow_tripdata